### ISSUE TITLE
ValueError while compiling

### ISSUE THREAD

**Issue by adityag6994** [gombru/iMaterialistFashion#1]
I am getting the following error while compiling it in NVIDIA DIGITS:
`ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
`I there some specific version of Python this works with ?

PS : thanks for the code :)

**Comment by gombru** [comment]
Compiling what? What do you want to do?

**Comment by adityag6994** [comment]
Oops I forgot to add the file.
[https://github.com/gombru/iMaterialistFashion/blob/ff27c8b8b50986ecdec983f979591dda68a18b06/googlenet_multilabel/FocalLoss.py](url)

I am adding this as custom layer in DIGITS, to use Focal Loss.

something like this : [https://github.com/NVIDIA/DIGITS/tree/master/examples/python-layer](url)

**Comment by adityag6994** [comment]
My bad, I was using it for multiple classes.
